/* ============================================================
   NGÂN HÀNG CÂU HỎI - AI LÀ TRIỆU PHÚ (MLN122)
   Nội dung bám sát "Sổ tay kiến thức" gồm 2 chương:
   - Chương I: 5 thời kỳ hình thành & phát triển Triết học Mác - Lênin
   - Chương II: 5 thời kỳ kinh tế Việt Nam qua lịch sử
   easy / medium / hard: mỗi thời kỳ đóng góp 2 câu / mức độ (10 thời kỳ x 2 = 20 câu / mức độ)
   Cấu trúc: q = câu hỏi, a = 4 đáp án, c = vị trí đáp án đúng (0-3), e = giải thích
   Phần sau dấu = là JSON thuần để các script khác đọc được.
   ============================================================ */
const QUESTION_BANK =
{
  "easy": [
    { "q": "Thời kỳ 1841-1844 trong sự hình thành triết học Mác - Lênin được gọi là thời kỳ gì?", "a": ["Thời kỳ hình thành tư tưởng triết học (bước quá độ)", "Thời kỳ đề xuất các nguyên lý duy vật biện chứng", "Thời kỳ Lênin bảo vệ và phát triển", "Thời kỳ bổ sung, phát triển toàn diện"], "c": 0, "e": "Đây là giai đoạn quá độ về tư tưởng của C.Mác và Ph.Ăngghen, từ chủ nghĩa duy tâm sang chủ nghĩa duy vật và chủ nghĩa cộng sản." },
    { "q": "Trong thời kỳ 1841-1844, C.Mác và Ph.Ăngghen chuyển từ lập trường nào sang lập trường nào?", "a": ["Từ chủ nghĩa duy vật sang chủ nghĩa duy tâm", "Từ chủ nghĩa duy tâm và dân chủ cách mạng sang chủ nghĩa duy vật và chủ nghĩa cộng sản", "Từ chủ nghĩa cộng sản sang chủ nghĩa xã hội không tưởng", "Từ chủ nghĩa duy vật siêu hình sang chủ nghĩa duy tâm khách quan"], "c": 1, "e": "Đây là bước quá độ tư tưởng căn bản, tạo tiền đề cho các nguyên lý triết học mới ra đời ở thời kỳ tiếp theo." },
    { "q": "Tác phẩm nào đánh dấu sự hoàn chỉnh, trình bày thế giới quan mới của Mác và Ăngghen một cách sáng sủa vào năm 1848?", "a": ["Tư bản", "Tuyên ngôn của Đảng Cộng sản", "Bút ký triết học", "Chống Đuy-rinh"], "c": 1, "e": "Tuyên ngôn của Đảng Cộng sản (1848) khép lại thời kỳ đề xuất những nguyên lý triết học duy vật biện chứng và duy vật lịch sử." },
    { "q": "Tác phẩm nào của C.Mác khẳng định vai trò cải tạo thế giới của thực tiễn?", "a": ["Luận cương về Phoiơbắc", "Nhà nước và cách mạng", "Biện chứng của tự nhiên", "Nguồn gốc của gia đình..."], "c": 0, "e": "Luận cương về Phoiơbắc (1845) là một trong những tác phẩm đặt nền móng cho thời kỳ đề xuất nguyên lý triết học mới (1845-1848)." },
    { "q": "Trong thời kỳ 1848-1895, C.Mác tập trung viết bộ tác phẩm nào?", "a": ["Tuyên ngôn của Đảng Cộng sản", "Tư bản", "Nhà nước và cách mạng", "Bút ký triết học"], "c": 1, "e": "C.Mác dành phần lớn thời kỳ bổ sung, phát triển toàn diện lý luận triết học (1848-1895) để viết bộ Tư bản." },
    { "q": "Ai là tác giả của 'Chống Đuy-rinh' và 'Biện chứng của tự nhiên'?", "a": ["C.Mác", "V.I.Lênin", "Ph.Ăngghen", "L.Phoiơbắc"], "c": 2, "e": "Ph.Ăngghen đóng góp những tác phẩm này trong thời kỳ 1848-1895, giúp trình bày học thuyết Mác thành hệ thống lý luận hoàn chỉnh." },
    { "q": "V.I.Lênin kế tục và phát triển triết học Mác trong điều kiện lịch sử nào?", "a": ["Thời đại đế quốc chủ nghĩa và quá độ lên chủ nghĩa xã hội", "Thời kỳ chủ nghĩa tư bản tự do cạnh tranh", "Thời kỳ Chiến tranh lạnh", "Thời kỳ toàn cầu hóa hiện nay"], "c": 0, "e": "Giai đoạn Lênin (cuối thế kỷ XIX - 1924) gắn với bối cảnh chủ nghĩa tư bản chuyển sang giai đoạn đế quốc chủ nghĩa." },
    { "q": "Tác phẩm nào của Lênin bảo vệ chủ nghĩa duy vật trước sự tấn công của chủ nghĩa duy tâm khi vật lý học có bước nhảy vọt?", "a": ["Bút ký triết học", "Chủ nghĩa duy vật và chủ nghĩa kinh nghiệm phê phán", "Nhà nước và cách mạng", "Làm gì?"], "c": 1, "e": "Tác phẩm này được Lênin viết để bảo vệ nền tảng duy vật của triết học Mác trước khủng hoảng thế giới quan trong khoa học tự nhiên." },
    { "q": "Sau khi V.I.Lênin mất (1924), triết học Mác - Lênin tiếp tục được ai bổ sung, phát triển?", "a": ["Chỉ riêng nước Nga", "Các Đảng Cộng sản và công nhân trên thế giới", "Không còn được ai phát triển", "Chỉ các nhà triết học phương Tây"], "c": 1, "e": "Từ 1924 đến nay, triết học Mác - Lênin tiếp tục được bổ sung dựa trên thực tiễn xây dựng chủ nghĩa xã hội và biến đổi của thời đại." },
    { "q": "Ai là người đã vận dụng sáng tạo triết học Mác - Lênin vào điều kiện cụ thể của Việt Nam?", "a": ["A.Smith", "Chủ tịch Hồ Chí Minh và Đảng Cộng sản Việt Nam", "D.Ricardo", "L.Phoiơbắc"], "c": 1, "e": "Hồ Chí Minh và Đảng Cộng sản Việt Nam đã vận dụng sáng tạo lý luận này để lãnh đạo cách mạng giải phóng dân tộc và công cuộc đổi mới." },
    { "q": "Ở thời kỳ cổ đại, phương thức trao đổi ban đầu giữa những người sản xuất là gì?", "a": ["Trao đổi trực tiếp hàng hóa lấy hàng hóa (H-H) mang tính ngẫu nhiên", "Trao đổi qua ngân hàng", "Trao đổi bằng tiền giấy", "Trao đổi qua sàn thương mại điện tử"], "c": 0, "e": "Đây là hình thái trao đổi sơ khai nhất trong kinh tế hàng hóa giản đơn thời cổ đại." },
    { "q": "Vật ngang giá chung cuối cùng được xã hội thống nhất sử dụng trong thời kỳ cổ đại là gì?", "a": ["Vỏ sò", "Gia súc", "Tiền vàng", "Tiền giấy"], "c": 2, "e": "Tiền vàng ra đời làm vật ngang giá chung thống nhất, kết thúc quá trình phát triển các hình thái giá trị thời cổ đại." },
    { "q": "Việt Nam bắt đầu áp dụng mô hình công nghiệp hóa theo kiểu Liên Xô (cũ) từ năm nào?", "a": ["1945", "1954", "1960", "1975"], "c": 2, "e": "Từ năm 1960, Việt Nam áp dụng mô hình công nghiệp hóa kiểu cũ, vận hành theo cơ chế kế hoạch hóa tập trung, mệnh lệnh." },
    { "q": "Trong thời kỳ sau Điện Biên Phủ, nền kinh tế miền Bắc vận hành theo cơ chế nào?", "a": ["Kinh tế thị trường tự do", "Kế hoạch hóa tập trung, mệnh lệnh", "Kinh tế thị trường định hướng XHCN", "Kinh tế thuộc địa"], "c": 1, "e": "Nhà nước nắm giữ và phân bổ các nguồn lực then chốt, ưu tiên phát triển công nghiệp nặng." },
    { "q": "Thời kỳ sau năm 1975 đến trước Đổi mới ở Việt Nam được gọi là thời kỳ gì?", "a": ["Thời kỳ thuộc địa", "Thời kỳ bao cấp", "Thời kỳ hội nhập quốc tế", "Thời kỳ cổ đại"], "c": 1, "e": "Đây là giai đoạn đỉnh cao của cơ chế kế hoạch hóa tập trung, bao cấp trên phạm vi cả nước." },
    { "q": "Trong thời kỳ bao cấp, nhà nước phân phối sản phẩm cho người dân chủ yếu theo hình thức nào?", "a": ["Mua bán tự do trên thị trường", "Chế độ tem phiếu", "Đấu giá công khai", "Thanh toán không tiền mặt"], "c": 1, "e": "Quan hệ hàng hóa - tiền tệ bị coi nhẹ; sản phẩm được phân phối theo chế độ tem phiếu." },
    { "q": "Trong thời kỳ thuộc địa, nền kinh tế Việt Nam lệ thuộc chủ yếu vào quốc gia nào?", "a": ["Nhật Bản", "Pháp", "Hoa Kỳ", "Liên Xô"], "c": 1, "e": "Các quan hệ kinh tế tại thuộc địa Việt Nam bị lệ thuộc hoàn toàn vào chính quốc là Pháp." },
    { "q": "Kinh tế thuộc địa Việt Nam thời Pháp thuộc chủ yếu xuất khẩu loại hàng hóa nào ra chính quốc?", "a": ["Hàng công nghiệp chế biến cao cấp", "Tài nguyên thô", "Công nghệ hiện đại", "Tiền tệ"], "c": 1, "e": "Việt Nam thời thuộc địa xuất khẩu tài nguyên thô và nhập khẩu hàng hóa công nghiệp từ chính quốc." },
    { "q": "Nền kinh tế Việt Nam từ thời kỳ Đổi mới đến nay được gọi là gì?", "a": ["Kinh tế kế hoạch hóa tập trung", "Kinh tế thị trường định hướng xã hội chủ nghĩa", "Kinh tế thuộc địa", "Kinh tế tự cấp tự túc"], "c": 1, "e": "Đây là mô hình kinh tế Việt Nam áp dụng từ công cuộc Đổi mới (1986) đến nay." },
    { "q": "Việt Nam là thành viên của những tổ chức quốc tế nào sau đây?", "a": ["WTO, ASEAN, APEC", "NATO, EU, G7", "Chỉ riêng OPEC", "Không tham gia tổ chức quốc tế nào"], "c": 0, "e": "Việt Nam hội nhập sâu rộng qua các tổ chức WTO, ASEAN, APEC và tham gia chuỗi giá trị toàn cầu." }
  ],
  "medium": [
    { "q": "Thông qua thực tiễn đấu tranh báo chí và nghiên cứu khoa học trong thời kỳ 1841-1844, C.Mác nhận ra điều gì quyết định hoạt động của nhà nước?", "a": ["Ý chí của giai cấp thống trị", "Các quan hệ khách quan - lợi ích vật chất", "Pháp luật và đạo đức", "Truyền thống văn hóa dân tộc"], "c": 1, "e": "Đây là phát hiện quan trọng giúp Mác chuyển sang lập trường duy vật trong thời kỳ hình thành tư tưởng triết học." },
    { "q": "Bước chuyển quyết định trong thời kỳ hình thành tư tưởng của Mác được đánh dấu bằng sự kiện nào?", "a": ["Xuất bản bộ Tư bản", "Các bài báo trên tạp chí Niên giám Pháp - Đức (1844)", "Công xã Pari", "Cách mạng Tháng Mười Nga"], "c": 1, "e": "Trong các bài báo này, Mác lần đầu chỉ ra giai cấp vô sản là lực lượng có sứ mệnh lịch sử." },
    { "q": "Tác phẩm nào trình bày một cách hệ thống quan điểm duy vật lịch sử?", "a": ["Bản thảo kinh tế - triết học 1844", "Hệ tư tưởng Đức", "Tư bản", "Chủ nghĩa duy vật và chủ nghĩa kinh nghiệm phê phán"], "c": 1, "e": "Hệ tư tưởng Đức (1845-1846) là nơi quan điểm duy vật lịch sử được C.Mác và Ph.Ăngghen trình bày có hệ thống." },
    { "q": "'Bản thảo kinh tế - triết học 1844' của C.Mác tập trung phân tích vấn đề gì?", "a": ["Lao động tha hóa", "Giá trị thặng dư", "Đấu tranh giai cấp", "Cách mạng vô sản"], "c": 0, "e": "Đây là một trong những tác phẩm quan trọng của thời kỳ đề xuất nguyên lý triết học mới (1845-1848)." },
    { "q": "Ngoài giá trị là công trình kinh tế, bộ 'Tư bản' còn được đánh giá là sự phát triển vĩ đại về lĩnh vực nào?", "a": ["Lôgíc học và triết học", "Sinh học và y học", "Toán học và vật lý học", "Ngôn ngữ học"], "c": 0, "e": "Bộ Tư bản không chỉ là công trình kinh tế mà còn là đóng góp lớn về lôgíc học và triết học duy vật biện chứng." },
    { "q": "Tác phẩm nào của Ph.Ăngghen trình bày nguồn gốc lịch sử của gia đình và nhà nước?", "a": ["Chống Đuy-rinh", "Biện chứng của tự nhiên", "Nguồn gốc của gia đình, của chế độ tư hữu và của nhà nước", "Hệ tư tưởng Đức"], "c": 2, "e": "Tác phẩm này thuộc thời kỳ 1848-1895, góp phần hoàn thiện hệ thống lý luận của học thuyết Mác." },
    { "q": "Tác phẩm nào của Lênin phát triển sâu sắc phép biện chứng duy vật?", "a": ["Bút ký triết học", "Nhà nước và cách mạng", "Chủ nghĩa duy vật và chủ nghĩa kinh nghiệm phê phán", "Chủ nghĩa đế quốc..."], "c": 0, "e": "Bút ký triết học là nơi Lênin phát triển sâu sắc phép biện chứng duy vật trong giai đoạn cuối TK XIX - 1924." },
    { "q": "Tác phẩm 'Nhà nước và cách mạng' của Lênin phục vụ trực tiếp cho sự kiện lịch sử nào?", "a": ["Công xã Pari 1871", "Cách mạng Tháng Mười Nga", "Chiến tranh thế giới thứ hai", "Cách mạng Tháng Tám ở Việt Nam"], "c": 1, "e": "Lý luận về nhà nước trong tác phẩm này phục vụ trực tiếp cho việc xây dựng nhà nước kiểu mới sau Cách mạng Tháng Mười." },
    { "q": "Tại Việt Nam, việc vận dụng sáng tạo triết học Mác - Lênin đã phục vụ trực tiếp cho những nhiệm vụ nào?", "a": ["Lãnh đạo cách mạng giải phóng dân tộc và thực hiện công cuộc đổi mới", "Chỉ phục vụ nghiên cứu học thuật", "Chỉ áp dụng trong lĩnh vực quân sự", "Không phục vụ nhiệm vụ thực tiễn nào"], "c": 0, "e": "Đây là hai nhiệm vụ lớn mà Hồ Chí Minh và Đảng Cộng sản Việt Nam đã vận dụng triết học Mác - Lênin để thực hiện." },
    { "q": "Đâu KHÔNG phải là một trong những đóng góp lý luận mới của Đảng Cộng sản Việt Nam trong thời kỳ 1924 đến nay?", "a": ["Lý luận về thời kỳ quá độ lên chủ nghĩa xã hội", "Phát triển kinh tế thị trường định hướng xã hội chủ nghĩa", "Xây dựng Nhà nước pháp quyền xã hội chủ nghĩa", "Phủ nhận vai trò lãnh đạo của Đảng Cộng sản"], "c": 3, "e": "Ba phương án đầu là các đóng góp lý luận thực tế; phủ nhận vai trò lãnh đạo của Đảng không phải là đóng góp lý luận của Đảng." },
    { "q": "Mục đích chính của việc trao đổi hàng hóa ở thời kỳ kinh tế hàng hóa giản đơn (cổ đại) là gì?", "a": ["Thu được giá trị sử dụng để thỏa mãn nhu cầu tiêu dùng trực tiếp của người sản xuất", "Tích lũy tư bản để mở rộng sản xuất", "Thu lợi nhuận tối đa", "Đầu cơ tích trữ hàng hóa"], "c": 0, "e": "Khác với sản xuất tư bản chủ nghĩa sau này, mục đích trao đổi thời cổ đại chủ yếu là thỏa mãn nhu cầu tiêu dùng." },
    { "q": "Trước khi hình thái chung của giá trị xuất hiện, hình thái giá trị đã trải qua bước phát triển nào?", "a": ["Hình thái tiền tệ", "Hình thái giá trị đầy đủ (mở rộng)", "Hình thái độc quyền", "Hình thái giá cả sản xuất"], "c": 1, "e": "Hình thái giá trị phát triển qua các bước: giản đơn (ngẫu nhiên) → đầy đủ (mở rộng) → chung → tiền tệ." },
    { "q": "Trong cơ chế kế hoạch hóa tập trung sau 1954, nhà nước ưu tiên phát triển ngành nào?", "a": ["Công nghiệp nhẹ", "Công nghiệp nặng", "Du lịch - dịch vụ", "Nông nghiệp xuất khẩu"], "c": 1, "e": "Mô hình công nghiệp hóa kiểu Liên Xô (cũ) mà Việt Nam áp dụng từ 1960 ưu tiên phát triển công nghiệp nặng." },
    { "q": "Việc trao đổi hàng hóa trong thời kỳ kế hoạch hóa tập trung (sau 1954) bị chi phối chủ yếu bởi yếu tố nào?", "a": ["Quan hệ cung - cầu trên thị trường tự do", "Chỉ tiêu kế hoạch do nhà nước phân bổ", "Cạnh tranh giữa các doanh nghiệp tư nhân", "Đầu tư nước ngoài"], "c": 1, "e": "Hàng hóa được phân phối theo chỉ tiêu kế hoạch thay vì vận hành theo quy luật cung - cầu của thị trường." },
    { "q": "Trong thời kỳ bao cấp, quan hệ hàng hóa - tiền tệ được nhìn nhận như thế nào?", "a": ["Được coi trọng và khuyến khích phát triển mạnh mẽ", "Bị coi nhẹ", "Được thay thế hoàn toàn bằng tiền điện tử", "Phát triển sôi động như kinh tế thị trường"], "c": 1, "e": "Đây là đặc trưng nổi bật của cơ chế bao cấp sau năm 1975, trước khi tiến hành Đổi mới." },
    { "q": "Mô hình kinh tế kế hoạch hóa tập trung sau 1975 được mở rộng ở phạm vi nào?", "a": ["Chỉ ở một vài tỉnh thành lớn", "Trên phạm vi cả nước", "Chỉ ở khu vực nông thôn", "Chỉ trong các doanh nghiệp có vốn nước ngoài"], "c": 1, "e": "Sau thống nhất đất nước 1975, mô hình kế hoạch hóa tập trung, bao cấp được mở rộng trên phạm vi cả nước." },
    { "q": "Chiều ngược lại, Việt Nam thời thuộc địa chủ yếu nhập khẩu gì từ Pháp?", "a": ["Nguyên liệu thô", "Hàng hóa công nghiệp từ chính quốc", "Lương thực", "Vàng bạc"], "c": 1, "e": "Việt Nam xuất khẩu tài nguyên thô và nhập khẩu ngược lại hàng hóa công nghiệp từ chính quốc Pháp." },
    { "q": "Về quan hệ sản xuất, nền kinh tế thuộc địa Việt Nam thời Pháp thuộc có đặc điểm gì?", "a": ["Thuần túy phong kiến, không có yếu tố tư bản", "Tồn tại các hình thái kinh tế hỗn hợp giữa phong kiến lạc hậu và tư bản chủ nghĩa sơ khai", "Kinh tế thị trường hiện đại hoàn chỉnh", "Kinh tế kế hoạch hóa tập trung"], "c": 1, "e": "Đây là đặc điểm quan hệ sản xuất điển hình của các nước thuộc địa nửa phong kiến như Việt Nam thời Pháp thuộc." },
    { "q": "Trong nền kinh tế thị trường định hướng XHCN hiện nay, các quan hệ sản xuất và trao đổi được thực hiện thông qua đâu và tuân theo quy luật nào?", "a": ["Qua mệnh lệnh hành chính, tuân theo chỉ tiêu kế hoạch", "Qua thị trường, tuân theo các quy luật kinh tế khách quan như quy luật giá trị, cung - cầu, cạnh tranh", "Qua chế độ tem phiếu", "Qua trao đổi hàng đổi hàng trực tiếp"], "c": 1, "e": "Đây là điểm khác biệt căn bản so với cơ chế kế hoạch hóa tập trung trước Đổi mới." },
    { "q": "Đặc trưng của công nghiệp hóa 4.0 trong nền kinh tế Việt Nam hiện nay là gì?", "a": ["Sản xuất dựa trên tri thức, dữ liệu và kết nối Internet vạn vật (IoT)", "Sản xuất thủ công truyền thống", "Chỉ dựa vào lao động giá rẻ", "Kế hoạch hóa tập trung toàn phần"], "c": 0, "e": "Công nghiệp hóa 4.0 là xu hướng phát triển kinh tế hiện nay của Việt Nam, gắn với tri thức, dữ liệu và IoT." }
  ],
  "hard": [
    { "q": "Trong các bài báo trên tạp chí Niên giám Pháp - Đức (1844), C.Mác lần đầu tiên chỉ ra điều gì có ý nghĩa bước ngoặt?", "a": ["Giai cấp vô sản là lực lượng xã hội có sứ mệnh lịch sử thực hiện cuộc cách mạng triệt để giải phóng nhân loại", "Giai cấp tư sản là động lực duy nhất của lịch sử", "Nhà nước sẽ tồn tại vĩnh viễn", "Tôn giáo là nền tảng đạo đức xã hội"], "c": 0, "e": "Đây là phát hiện then chốt của C.Mác, đánh dấu bước chuyển quyết định trong thời kỳ hình thành tư tưởng triết học (1841-1844)." },
    { "q": "Thời kỳ 1841-1844 có vai trò gì trong toàn bộ quá trình hình thành triết học Mác?", "a": ["Là thời kỳ hoàn thiện học thuyết", "Là bước quá độ về tư tưởng, tạo tiền đề để xây dựng những nguyên lý triết học mới ở thời kỳ tiếp theo", "Là thời kỳ Lênin phát triển triết học", "Không có vai trò gì đáng kể"], "c": 1, "e": "Thời kỳ này là nền móng tư tưởng, chuẩn bị cho thời kỳ đề xuất nguyên lý triết học duy vật biện chứng và duy vật lịch sử (1845-1848)." },
    { "q": "Thời kỳ 1845-1848 có ý nghĩa như thế nào đối với hệ thống triết học của Mác và Ăngghen?", "a": ["Là thời kỳ hai ông tự giải phóng mình khỏi hệ thống triết học cũ và xây dựng những nguyên lý nền tảng cho một thế giới quan mới", "Là thời kỳ hai ông quay lại với triết học Hêghen", "Là thời kỳ hai ông ngừng nghiên cứu triết học để làm kinh tế", "Là thời kỳ Lênin kế thừa tư tưởng của hai ông"], "c": 0, "e": "Đây là thời kỳ bản lề, đặt nền móng lý luận cho toàn bộ hệ thống triết học Mác sau này." },
    { "q": "Trình tự ra đời (từ sớm đến muộn) của các tác phẩm sau là gì: Tuyên ngôn của Đảng Cộng sản, Hệ tư tưởng Đức, Bản thảo kinh tế - triết học 1844?", "a": ["Bản thảo KT-triết 1844 → Hệ tư tưởng Đức → Tuyên ngôn Đảng Cộng sản", "Tuyên ngôn Đảng Cộng sản → Hệ tư tưởng Đức → Bản thảo KT-triết 1844", "Hệ tư tưởng Đức → Bản thảo KT-triết 1844 → Tuyên ngôn Đảng Cộng sản", "Cả ba ra đời cùng năm 1848"], "c": 0, "e": "Thứ tự đúng theo mốc thời gian: 1844 → 1845-1846 → 1848." },
    { "q": "Trong thời kỳ 1848-1895, học thuyết Mác được bổ sung và phát triển trên cơ sở nào?", "a": ["Chỉ dựa trên suy luận thuần túy lý thuyết", "Tổng kết thực tiễn các phong trào cách mạng và khái quát các thành tựu khoa học mới", "Kế thừa nguyên vẹn triết học Hêghen", "Phủ nhận toàn bộ kinh tế chính trị học cổ điển"], "c": 1, "e": "Đây là phương pháp phát triển lý luận đặc trưng của học thuyết Mác trong thời kỳ bổ sung, phát triển toàn diện." },
    { "q": "Vai trò của Ph.Ăngghen trong thời kỳ 1848-1895 được thể hiện chủ yếu ở điểm nào?", "a": ["Giúp trình bày học thuyết Mác dưới dạng một hệ thống lý luận hoàn chỉnh qua các tác phẩm của mình", "Chỉ hỗ trợ tài chính cho C.Mác", "Không có đóng góp lý luận nào", "Tập trung hoàn toàn vào hoạt động báo chí"], "c": 0, "e": "Qua các tác phẩm như Chống Đuy-rinh, Biện chứng của tự nhiên, Ăngghen góp phần hệ thống hóa toàn bộ học thuyết Mác." },
    { "q": "Bối cảnh khoa học tự nhiên nào đặt ra thách thức buộc Lênin phải bảo vệ chủ nghĩa duy vật trong tác phẩm 'Chủ nghĩa duy vật và chủ nghĩa kinh nghiệm phê phán'?", "a": ["Sự khủng hoảng về thế giới quan khi vật lý học có những phát hiện mới bị các trào lưu duy tâm lợi dụng xuyên tạc", "Sự ra đời của thuyết tiến hóa Đácuyn", "Sự phát triển của toán học thống kê", "Sự khủng hoảng của kinh tế học cổ điển"], "c": 0, "e": "Những phát hiện mới của vật lý học cuối TK XIX - đầu TK XX bị chủ nghĩa duy tâm lợi dụng, đòi hỏi Lênin phải bảo vệ nền tảng duy vật." },
    { "q": "Đóng góp của Lênin trong giai đoạn cuối thế kỷ XIX - 1924 đối với triết học Mác có đặc điểm gì nổi bật?", "a": ["Chỉ lặp lại nguyên vẹn tư tưởng của Mác - Ăngghen mà không phát triển thêm", "Bảo vệ, vận dụng và phát triển sáng tạo triết học Mác gắn liền với thực tiễn đấu tranh cách mạng và xây dựng nhà nước kiểu mới", "Tách rời triết học khỏi thực tiễn cách mạng", "Chuyển trọng tâm nghiên cứu sang kinh tế học thuần túy"], "c": 1, "e": "Lênin không chỉ bảo vệ mà còn phát triển sáng tạo triết học Mác, gắn lý luận với thực tiễn Cách mạng Tháng Mười Nga." },
    { "q": "Sự phát triển của triết học Mác - Lênin từ 1924 đến nay dựa trên cơ sở nào là chủ yếu?", "a": ["Thực tiễn xây dựng chủ nghĩa xã hội và những biến đổi của thời đại", "Chỉ dựa trên các tác phẩm kinh điển đã có, không bổ sung gì thêm", "Sự sụp đổ hoàn toàn của mô hình chủ nghĩa xã hội", "Việc phủ nhận toàn bộ tư tưởng của Mác và Lênin"], "c": 0, "e": "Các Đảng Cộng sản trên thế giới, trong đó có Việt Nam, tiếp tục phát triển lý luận dựa trên thực tiễn xây dựng CNXH." },
    { "q": "Nhận định nào sau đây phản ánh đúng nhất tinh thần vận dụng triết học Mác - Lênin ở Việt Nam?", "a": ["Vận dụng máy móc, giữ nguyên mọi luận điểm gốc", "Vận dụng sáng tạo, gắn lý luận với điều kiện lịch sử cụ thể của đất nước", "Chỉ vận dụng trong giai đoạn chiến tranh, không áp dụng thời bình", "Thay thế hoàn toàn bằng lý luận khác từ thời kỳ đổi mới"], "c": 1, "e": "Hồ Chí Minh và Đảng Cộng sản Việt Nam luôn nhấn mạnh tinh thần vận dụng sáng tạo, không giáo điều, máy móc." },
    { "q": "Sự vận động của các hình thái giá trị trong thời kỳ cổ đại (từ trao đổi ngẫu nhiên đến vật ngang giá chung rồi tiền vàng) phản ánh quy luật gì?", "a": ["Sự phát triển tất yếu của sản xuất và trao đổi hàng hóa, dẫn tới sự ra đời khách quan của tiền tệ", "Sự can thiệp chủ quan, áp đặt của nhà nước phong kiến", "Sự sụp đổ của kinh tế tự nhiên", "Kết quả của cách mạng công nghiệp"], "c": 0, "e": "Tiền tệ ra đời một cách khách quan, tất yếu từ chính sự phát triển của sản xuất và trao đổi hàng hóa, không phải do áp đặt chủ quan." },
    { "q": "Điểm khác biệt căn bản giữa kinh tế hàng hóa giản đơn thời cổ đại với kinh tế thị trường hiện đại là gì?", "a": ["Kinh tế hàng hóa giản đơn không có trao đổi", "Kinh tế hàng hóa giản đơn nhằm thỏa mãn nhu cầu tiêu dùng trực tiếp là chính, quy mô nhỏ lẻ, chưa vận hành đầy đủ theo các quy luật thị trường hiện đại", "Kinh tế hàng hóa giản đơn dùng tiền điện tử", "Không có sự khác biệt nào"], "c": 1, "e": "Kinh tế thị trường hiện đại vận hành đầy đủ theo quy luật giá trị, cung - cầu, cạnh tranh ở quy mô lớn, khác với trao đổi giản đơn thời cổ đại." },
    { "q": "Vì sao giai đoạn công nghiệp hóa sau Điện Biên Phủ được gọi là 'mô hình kiểu cũ'?", "a": ["Vì sao chép mô hình Liên Xô, chưa hoàn toàn phù hợp điều kiện Việt Nam, vận hành theo cơ chế kế hoạch hóa tập trung thay vì quy luật thị trường", "Vì đây là mô hình hoàn toàn mới do Việt Nam tự sáng tạo", "Vì mô hình này áp dụng cơ chế thị trường tự do hoàn toàn", "Vì mô hình này chỉ áp dụng cho miền Nam"], "c": 0, "e": "Mô hình này được gọi là 'kiểu cũ' vì sao chép theo kiểu Liên Xô, vận hành bằng kế hoạch hóa - mệnh lệnh thay vì theo quy luật thị trường." },
    { "q": "Đặc điểm nào sau đây KHÔNG đúng với nền kinh tế Việt Nam thời kỳ sau Điện Biên Phủ theo mô hình kiểu cũ?", "a": ["Nhà nước nắm giữ và phân bổ các nguồn lực then chốt", "Thị trường chưa phát triển đầy đủ", "Ưu tiên phát triển công nghiệp nặng", "Vận hành hoàn toàn theo quy luật cung - cầu của thị trường tự do"], "c": 3, "e": "Đặc trưng của mô hình kiểu cũ là kế hoạch hóa tập trung, mệnh lệnh - trái ngược hoàn toàn với vận hành theo thị trường tự do." },
    { "q": "Hệ quả của mô hình kinh tế kế hoạch hóa tập trung, bao cấp sau một thời gian dài duy trì là gì?", "a": ["Nền kinh tế phát triển vượt bậc và thịnh vượng", "Bộc lộ sự không thích ứng với trình độ khoa học - kỹ thuật mới, dẫn đến trì trệ và khủng hoảng kinh tế", "Không có hệ quả đáng kể nào", "Việt Nam trở thành nước xuất khẩu công nghệ hàng đầu"], "c": 1, "e": "Chính hệ quả trì trệ, khủng hoảng này đã đặt ra yêu cầu tất yếu phải tiến hành công cuộc Đổi mới." },
    { "q": "Chính hệ quả trì trệ, khủng hoảng của thời kỳ bao cấp đã đặt ra yêu cầu tất yếu nào cho Việt Nam?", "a": ["Tiếp tục duy trì nguyên trạng mô hình cũ", "Tiến hành công cuộc đổi mới, chuyển sang kinh tế thị trường định hướng xã hội chủ nghĩa", "Quay trở lại mô hình kinh tế thời thuộc địa", "Đóng cửa hoàn toàn nền kinh tế, không giao thương với bên ngoài"], "c": 1, "e": "Đại hội VI (1986) của Đảng đã khởi xướng công cuộc đổi mới toàn diện, chuyển sang phát triển kinh tế hàng hóa nhiều thành phần." },
    { "q": "Kinh tế thuộc địa thời Pháp thuộc được xem là một phần của mô hình nào trong lịch sử công nghiệp hóa thế giới?", "a": ["Mô hình công nghiệp hóa cổ điển - nơi các nước tư bản chiếm hữu và cướp bóc thuộc địa để khai thác lao động, tài nguyên", "Mô hình công nghiệp hóa 4.0", "Mô hình kinh tế thị trường định hướng xã hội chủ nghĩa", "Mô hình kế hoạch hóa tập trung kiểu Liên Xô"], "c": 0, "e": "Đây là đặc trưng chung của các nước tư bản phương Tây trong mô hình công nghiệp hóa cổ điển, gắn với khai thác thuộc địa." },
    { "q": "Vì sao có thể nói quan hệ kinh tế thời thuộc địa mang tính chất bất bình đẳng?", "a": ["Vì Việt Nam bị buộc đóng vai trò cung cấp nguyên liệu thô giá rẻ và tiêu thụ hàng hóa công nghiệp từ chính quốc, phục vụ lợi ích của tầng lớp thực dân", "Vì hai bên trao đổi hàng hóa ngang giá hoàn toàn", "Vì Việt Nam được tự do định đoạt chính sách thương mại", "Vì không có quan hệ trao đổi kinh tế nào giữa hai bên"], "c": 0, "e": "Cấu trúc trao đổi này chỉ phục vụ lợi ích của chính quốc và tầng lớp thực dân, không nhằm phát triển kinh tế bản địa." },
    { "q": "Vai trò của nhà nước trong nền kinh tế thị trường định hướng XHCN hiện nay khác gì so với thời kỳ bao cấp?", "a": ["Nhà nước không còn quản lý trực tiếp bằng mệnh lệnh mà đóng vai trò điều tiết, tạo môi trường thuận lợi cho các thành phần kinh tế cùng phát triển bình đẳng", "Nhà nước hoàn toàn không còn vai trò gì trong nền kinh tế", "Nhà nước quay lại phân phối bằng chế độ tem phiếu", "Nhà nước độc quyền toàn bộ hoạt động sản xuất kinh doanh"], "c": 0, "e": "Đây là sự chuyển đổi căn bản về vai trò của nhà nước so với cơ chế kế hoạch hóa tập trung, mệnh lệnh trước Đổi mới." },
    { "q": "Sự phát triển của các công cụ trao đổi hiện nay (tiền ghi sổ, tài khoản ngân hàng, tiền điện tử) so với thời kỳ cổ đại (vật ngang giá chung, tiền vàng) phản ánh điều gì?", "a": ["Sự vận động, phát triển tất yếu của hình thái tiền tệ theo trình độ phát triển của lực lượng sản xuất và công nghệ qua từng thời kỳ lịch sử", "Sự thụt lùi trong phát triển kinh tế", "Sự quay trở lại hình thái trao đổi hàng đổi hàng nguyên thủy", "Không có mối liên hệ gì với các hình thái tiền tệ trước đây"], "c": 0, "e": "Từ vật ngang giá chung, tiền vàng đến tiền ghi sổ, tiền điện tử - tất cả đều là các nấc thang phát triển tất yếu của hình thái tiền tệ." }
  ]
}
;
